/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import Logica.Lugares;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JDaniel
 */
public class frmLugares extends javax.swing.JFrame {

    /**
     * Creates new form frmLugares
     */
    public List<Lugares> listado;

    public DefaultTableModel modelo;
    
    public frmLugares() {
        initComponents();
     
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAgregarLugar = new javax.swing.JButton();
        BtnEditarLugar = new javax.swing.JButton();
        BtnEliminarLugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUGARES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Lugar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnAgregarLugar.setText("Agregar lugar");
        BtnAgregarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarLugarActionPerformed(evt);
            }
        });

        BtnEditarLugar.setText("Editar Lugar");
        BtnEditarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarLugarActionPerformed(evt);
            }
        });

        BtnEliminarLugar.setText("Eliminar Lugar");
        BtnEliminarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarLugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEliminarLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(BtnEditarLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgregarLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BtnAgregarLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEditarLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminarLugar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarLugarActionPerformed
        // TODO add your handling code here:
        String Nom = "";
        Nom = JOptionPane.showInputDialog("Digite el nombre del lugar que desea agregar:");
     
        llenarTabla();
    }//GEN-LAST:event_BtnAgregarLugarActionPerformed

    private void BtnEditarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarLugarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String codigo = "",nombre = "";
        
        if (fila >= 0){
            codigo = jTable1.getValueAt(fila, 0).toString();
            nombre = JOptionPane.showInputDialog("Digite el nombre del lugar: ");
          
            llenarTabla();
        }
        else {
            JOptionPane.showMessageDialog(null,"Tiene que seleccionar el lugar que desea editar","AVISO",JOptionPane.ERROR);
        }
    }//GEN-LAST:event_BtnEditarLugarActionPerformed

    private void BtnEliminarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarLugarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String codigo = "";
        
        if (fila >= 0){
            codigo = jTable1.getValueAt(fila, 0).toString();
        
            llenarTabla();
        }
        else {
            JOptionPane.showMessageDialog(null,"Tiene que seleccionar el lugar que desea eliminar","AVISO",JOptionPane.ERROR);
        }
        
    }//GEN-LAST:event_BtnEliminarLugarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void llenarTabla(){
        String[] nombres = {"Codigo","Lugares"};
        modelo = new DefaultTableModel(null, nombres);
     
        String[] lugar = new String[2];
        for (int i = 0; i < listado.size(); i++) {
            lugar[0] = listado.get(i).getCodigo();
            lugar[1] = listado.get(i).getlugar();
            modelo.addRow(lugar);
        }
        jTable1.setModel(modelo);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLugares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarLugar;
    private javax.swing.JButton BtnEditarLugar;
    private javax.swing.JButton BtnEliminarLugar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
